sky:
  datasource: #自定义数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 2333
  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id: LTAI5tJmdQfHwTByeVcHZYXj
    access-key-secret: U5GEG58wOHz2rcrEGFdOls1NbSlQZC
    bucket-name: sktlsgbucket
